version: '2'
services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    volumes:
      - my-named-db
    ports:
      - 27017:27017
    networks:
      - backend
  simple-mart:
    container_name: simple_mart
    image: swapnildocker777/simple_mart:MongoDB
    ports:
      - 8082:8082
    networks:
      - backend
    restart: unless-stopped
#  db:
#    container_name: my_postgres
#    image: postgres:14.1
#    environment:
#      POSTGRES_USER: swapnil
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5332:5432"
#    networks:
#      - db
#    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  my-named-db: